name: back_end
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  google_fonts: ^4.0.3
  file_picker: ^5.3.1
  firebase_analytics: ^10.4.2
  fluttertoast: ^8.0.8
  firebase_auth_web: ^5.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - image/
  
 
